In [1]:
# Automatic differentiation 自动微分

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
# ts 在 tape 中记录执行的前向执行的顺序，随后反向求梯度
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x ** 2

In [3]:
# 记住了操作之后就可以使用 gradient api 求梯度
# dy = 2x * dx

dy_dx = tape.gradient(y, x) # (target, source)
dy_dx.numpy()

6.0

In [4]:
w = tf.Variable(tf.random.normal((3, 2)), name='w')
b = tf.Variable(tf.zeros(2, dtype=tf.float32), name='b')
x = [[1., 2., 3.]]
print(w, b)

with tf.GradientTape(persistent=True) as tape:
  y = x @ w + b
  loss = tf.reduce_mean(y**2) # 求均值

<tf.Variable 'w:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.18612899,  1.8958843 ],
       [ 0.7443945 ,  0.3573219 ],
       [ 1.3322434 , -0.54626733]], dtype=float32)> <tf.Variable 'b:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [5]:
[dl_dw, dl_db] = tape.gradient(loss, [w, b])
print(dl_dw, dl_db)

tf.Tensor(
[[ 5.671648    0.97172594]
 [11.343296    1.9434519 ]
 [17.014944    2.9151778 ]], shape=(3, 2), dtype=float32) tf.Tensor([5.671648   0.97172594], shape=(2,), dtype=float32)


In [7]:
my_vars = {
    'w': w,
    'b': b
}

grad = tape.gradient(loss, my_vars)
print(grad['w'], grad['b'])

tf.Tensor(
[[ 5.671648    0.97172594]
 [11.343296    1.9434519 ]
 [17.014944    2.9151778 ]], shape=(3, 2), dtype=float32) tf.Tensor([5.671648   0.97172594], shape=(2,), dtype=float32)
